### ISSUE TITLE
Missing code for consensus programs 

### ISSUE THREAD

**Issue by ccruizm** [BernsteinLab/Myeloid-Glioma#1]
Good day!

I am interested in applying a similar approach to my dataset using cNMF and would like to know how you determined the consensus programs after identifying each cNMF per cohort. Scripts are nicely enumerated, and all contain the code for performing the analyses except ‘11- Identifying consensus programs’ (the one I am particularly interested in). Do you have an updated version of this notebook?
 
Many thanks for considering my request.

**Comment by chadielfarran** [comment]
The issue has been solved. Thank you for pointing it out
